In [ ]:
!pip install -q kaggle
import json

data = {"username":"tunkedsaro","key":"ff3d00dc680ff94caf6f8d4d9bcd3168"}
json_data = json.dumps(data)

# Write the JSON string to a file
file_path = "/content/kaggle.json"
with open(file_path, 'w') as json_file:
    json_file.write(json_data)

!mkdir ~/.kaggle
!cp /content/kaggle.json ~/.kaggle/ #copy api key ---- depend on your directory -- my directory is .../colab/..
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets list
!kaggle competitions download -c hackathon-online-data-science-mini-epidemiology
!unzip -q /content/hackathon-online-data-science-mini-epidemiology.zip

ref                                                           title                                            size  lastUpdated          downloadCount  voteCount  usabilityRating
------------------------------------------------------------  ----------------------------------------------  -----  -------------------  -------------  ---------  ---------------
patricklford/global-ev-sales-2010-2024                        Global EV Sales: 2010-2024                       83KB  2024-07-19 13:40:22           1889         27  1.0
marius2303/nissan-all-models-price-prediction-dataset         Nissan All Models Price Prediction Dataset      811KB  2024-07-27 11:50:10            915         24  1.0
waqi786/global-air-quality-dataset                            Global Air Quality Dataset üåçüå´Ô∏è                  258KB  2024-07-28 10:35:09           1272         29  1.0
waqi786/1000-richest-people-in-the-world                      1000 Richest People in the World                  8KB  2024-07-28 05:39:38           1106         31  1.0
rabieelkharoua/students-performance-dataset                   üìö Students Performance Dataset üìö                 66KB  2024-06-12 23:09:20          25905        516  1.0
rasikasrimal/covid-19-confirmed-cases                         covid-19 confirmed cases                         30KB  2024-07-18 12:04:09            974         22  1.0
ihelon/coffee-sales                                           Coffee Sales                                     13KB  2024-08-01 07:55:34           8885        143  1.0
nelgiriyewithana/most-streamed-spotify-songs-2024             Most Streamed Spotify Songs 2024                496KB  2024-06-15 18:50:51          18875        372  1.0
waqi786/cars-dataset-2010-2020                                Cars Dataset (2010-2020)                         96KB  2024-07-23 05:49:46           1584         29  1.0
waqi786/titanic-dataset                                       Titanic Dataset                                  41KB  2024-07-25 08:23:03            674         22  1.0
waqi786/mobile-sales-dataset                                  Mobile Sales Dataset üì±                           58KB  2024-07-26 11:03:16           1381         32  1.0
ganjerlawrence/mobile-phone-price-prediction-cleaned-dataset  Mobile Phone Price Prediction cleaned Dataset     5KB  2024-06-30 11:56:32           1637         26  1.0
waqi786/e-commerce-clickstream-and-transaction-dataset        E-commerce Clickstream and Transaction Dataset    1MB  2024-07-24 10:17:49            985         31  1.0
waqi786/movies-dataset-1980-2020                              Movies Dataset (1980-2020)                      645KB  2024-07-22 13:49:26           1603         36  1.0
waqi786/top-intelligent-people-in-the-world                   Top Intelligent People in the World üåçüß†           79KB  2024-07-27 11:36:16            740         29  1.0
harinkl/import-and-export-of-india-2009-2025                  import and export of india 2009-2025            364KB  2024-07-20 04:37:38           1634         27  1.0
waqi786/student-performance-dataset                           üìö Student Performance Dataset üìö                   6KB  2024-07-26 04:24:34           1026         34  1.0
akinduhiman/trending-youtube-videos-2019-to-2020              Trending YouTube Videos 2019 to 2020             26MB  2024-07-24 19:21:40            813         26  1.0
abhayayare/flower-dataset                                     Flower Dataset                                   40KB  2024-07-25 17:58:23            660         24  1.0
wajahat1064/amazon-reviews-data-2023                          Amazon Reviews Data 2023                        271MB  2024-07-25 18:50:12            482         21  1.0
Downloading hackathon-online-data-science-mini-epidemiology.zip to /content
100% 274k/274k [00:00<00:00, 440kB/s]
100% 274k/274k [00:00<00:00, 440kB/s]

In [ ]:
!pip -q install autogluon.tabular

     ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 60.4/60.4 kB 5.1 MB/s eta 0:00:00
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 312.1/312.1 kB 27.7 MB/s eta 0:00:00
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 234.8/234.8 kB 22.4 MB/s eta 0:00:00
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 63.4/63.4 kB 6.5 MB/s eta 0:00:00
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 64.6/64.6 kB 6.7 MB/s eta 0:00:00
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 38.4/38.4 MB 54.2 MB/s eta 0:00:00
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 139.2/139.2 kB 14.0 MB/s eta 0:00:00
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 12.4/12.4 MB 119.4 MB/s eta 0:00:00
   ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 82.7/82.7 kB 8.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xgboost 2.1.0 requires nvidia-nccl-cu12; platform_system == "Linux" and platform_machine != "aarch64", which is not installed.
osqp 0.6.7.post0 requires scipy!=1.12.0,>=0.13.2, but you have scipy 1.12.0 which is incompatible.

In [1]:
import torch
print("GPU available:", torch.cuda.is_available())

GPU available: True

In [2]:
!pip install autogluon --upgrade

Requirement already satisfied: autogluon in /usr/local/lib/python3.10/dist-packages (1.1.1)
Requirement already satisfied: autogluon.core==1.1.1 in /usr/local/lib/python3.10/dist-packages (from autogluon.core[all]==1.1.1->autogluon) (1.1.1)
Requirement already satisfied: autogluon.features==1.1.1 in /usr/local/lib/python3.10/dist-packages (from autogluon) (1.1.1)
Requirement already satisfied: autogluon.tabular==1.1.1 in /usr/local/lib/python3.10/dist-packages (from autogluon.tabular[all]==1.1.1->autogluon) (1.1.1)
Requirement already satisfied: autogluon.multimodal==1.1.1 in /usr/local/lib/python3.10/dist-packages (from autogluon) (1.1.1)
Requirement already satisfied: autogluon.timeseries==1.1.1 in /usr/local/lib/python3.10/dist-packages (from autogluon.timeseries[all]==1.1.1->autogluon) (1.1.1)
Requirement already satisfied: numpy<1.29,>=1.21 in /usr/local/lib/python3.10/dist-packages (from autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (1.26.4)
Requirement already satisfied: scipy<1.13,>=1.5.4 in /usr/local/lib/python3.10/dist-packages (from autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (1.12.0)
Requirement already satisfied: scikit-learn<1.4.1,>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (1.3.2)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.10/dist-packages (from autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (3.3)
Requirement already satisfied: pandas<2.3.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (2.1.4)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.10/dist-packages (from autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (4.66.4)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (2.32.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (3.7.1)
Requirement already satisfied: boto3<2,>=1.10 in /usr/local/lib/python3.10/dist-packages (from autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (1.34.152)
Requirement already satisfied: autogluon.common==1.1.1 in /usr/local/lib/python3.10/dist-packages (from autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (1.1.1)
Requirement already satisfied: ray<2.11,>=2.10.0 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<2.11,>=2.10.0; extra == "all"->autogluon.core[all]==1.1.1->autogluon) (2.10.0)
Requirement already satisfied: hyperopt<0.2.8,>=0.2.7 in /usr/local/lib/python3.10/dist-packages (from autogluon.core[all]==1.1.1->autogluon) (0.2.7)
Requirement already satisfied: Pillow<11,>=10.0.1 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (10.4.0)
Requirement already satisfied: torch<2.4,>=2.2 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (2.3.1+cu121)
Requirement already satisfied: lightning<2.4,>=2.2 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (2.3.3)
Requirement already satisfied: transformers<4.41.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from transformers[sentencepiece]<4.41.0,>=4.38.0->autogluon.multimodal==1.1.1->autogluon) (4.39.3)
Requirement already satisfied: accelerate<0.22.0,>=0.21.0 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (0.21.0)
Requirement already satisfied: jsonschema<4.22,>=4.18 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (4.21.1)
Requirement already satisfied: seqeval<1.3.0,>=1.2.2 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (1.2.2)
Requirement already satisfied: evaluate<0.5.0,>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (0.4.2)
Requirement already satisfied: timm<0.10.0,>=0.9.5 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (0.9.16)
Requirement already satisfied: torchvision<0.19.0,>=0.16.0 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (0.18.1+cu121)
Requirement already satisfied: scikit-image<0.21.0,>=0.19.1 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (0.20.0)
Requirement already satisfied: text-unidecode<1.4,>=1.3 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (1.3)
Requirement already satisfied: torchmetrics<1.3.0,>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (1.2.1)
Requirement already satisfied: nptyping<2.5.0,>=1.4.4 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (2.4.1)
Requirement already satisfied: omegaconf<2.3.0,>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (2.2.3)
Requirement already satisfied: pytorch-metric-learning<2.4,>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (2.3.0)
Requirement already satisfied: nlpaug<1.2.0,>=1.1.10 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (1.1.11)
Requirement already satisfied: nltk<4.0.0,>=3.4.5 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (3.8.1)
Requirement already satisfied: openmim<0.4.0,>=0.3.7 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (0.3.9)
Requirement already satisfied: defusedxml<0.7.2,>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (0.7.1)
Requirement already satisfied: jinja2<3.2,>=3.0.3 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (3.1.4)
Requirement already satisfied: tensorboard<3,>=2.9 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (2.17.0)
Requirement already satisfied: pytesseract<0.3.11,>=0.3.9 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (0.3.10)
Requirement already satisfied: nvidia-ml-py3==7.352.0 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (7.352.0)
Requirement already satisfied: pdf2image<1.19,>=1.17.0 in /usr/local/lib/python3.10/dist-packages (from autogluon.multimodal==1.1.1->autogluon) (1.17.0)
Requirement already satisfied: xgboost<2.1,>=1.6 in /usr/local/lib/python3.10/dist-packages (from autogluon.tabular[all]==1.1.1->autogluon) (2.0.3)
Requirement already satisfied: fastai<2.8,>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from autogluon.tabular[all]==1.1.1->autogluon) (2.7.15)
Requirement already satisfied: lightgbm<4.4,>=3.3 in /usr/local/lib/python3.10/dist-packages (from autogluon.tabular[all]==1.1.1->autogluon) (4.3.0)
Requirement already satisfied: catboost<1.3,>=1.1 in /usr/local/lib/python3.10/dist-packages (from autogluon.tabular[all]==1.1.1->autogluon) (1.2.5)
Requirement already satisfied: joblib<2,>=1.1 in /usr/local/lib/python3.10/dist-packages (from autogluon.timeseries==1.1.1->autogluon.timeseries[all]==1.1.1->autogluon) (1.4.2)
Requirement already satisfied: pytorch-lightning<2.4,>=2.2 in /usr/local/lib/python3.10/dist-packages (from autogluon.timeseries==1.1.1->autogluon.timeseries[all]==1.1.1->autogluon) (2.3.3)
Requirement already satisfied: gluonts==0.15.1 in /usr/local/lib/python3.10/dist-packages (from autogluon.timeseries==1.1.1->autogluon.timeseries[all]==1.1.1->autogluon) (0.15.1)
Requirement already satisfied: statsforecast<1.5,>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from autogluon.timeseries==1.1.1->autogluon.timeseries[all]==1.1.1->autogluon) (1.4.0)
Requirement already satisfied: mlforecast<0.10.1,>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from autogluon.timeseries==1.1.1->autogluon.timeseries[all]==1.1.1->autogluon) (0.10.0)
Requirement already satisfied: utilsforecast<0.0.11,>=0.0.10 in /usr/local/lib/python3.10/dist-packages (from autogluon.timeseries==1.1.1->autogluon.timeseries[all]==1.1.1->autogluon) (0.0.10)
Requirement already satisfied: orjson~=3.9 in /usr/local/lib/python3.10/dist-packages (from autogluon.timeseries==1.1.1->autogluon.timeseries[all]==1.1.1->autogluon) (3.10.6)
Requirement already satisfied: optimum<1.19,>=1.17 in /usr/local/lib/python3.10/dist-packages (from optimum[onnxruntime]<1.19,>=1.17; extra == "all"->autogluon.timeseries[all]==1.1.1->autogluon) (1.18.1)
Requirement already satisfied: psutil<6,>=5.7.3 in /usr/local/lib/python3.10/dist-packages (from autogluon.common==1.1.1->autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (5.9.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from autogluon.common==1.1.1->autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (71.0.4)
Requirement already satisfied: pydantic<3,>=1.7 in /usr/local/lib/python3.10/dist-packages (from gluonts==0.15.1->autogluon.timeseries==1.1.1->autogluon.timeseries[all]==1.1.1->autogluon) (2.8.2)
Requirement already satisfied: toolz~=0.10 in /usr/local/lib/python3.10/dist-packages (from gluonts==0.15.1->autogluon.timeseries==1.1.1->autogluon.timeseries[all]==1.1.1->autogluon) (0.12.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.10/dist-packages (from gluonts==0.15.1->autogluon.timeseries==1.1.1->autogluon.timeseries[all]==1.1.1->autogluon) (4.12.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate<0.22.0,>=0.21.0->autogluon.multimodal==1.1.1->autogluon) (24.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate<0.22.0,>=0.21.0->autogluon.multimodal==1.1.1->autogluon) (6.0.1)
Requirement already satisfied: botocore<1.35.0,>=1.34.152 in /usr/local/lib/python3.10/dist-packages (from boto3<2,>=1.10->autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (1.34.152)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from boto3<2,>=1.10->autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from boto3<2,>=1.10->autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (0.10.2)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost<1.3,>=1.1->autogluon.tabular[all]==1.1.1->autogluon) (0.20.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost<1.3,>=1.1->autogluon.tabular[all]==1.1.1->autogluon) (5.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost<1.3,>=1.1->autogluon.tabular[all]==1.1.1->autogluon) (1.16.0)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.1.1->autogluon) (2.20.0)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.1.1->autogluon) (0.3.8)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.1.1->autogluon) (3.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.1.1->autogluon) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]>=2021.05.0->evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.1.1->autogluon) (2024.5.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from evaluate<0.5.0,>=0.4.0->autogluon.multimodal==1.1.1->autogluon) (0.23.5)
Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==1.1.1->autogluon) (24.1.2)
Requirement already satisfied: fastdownload<2,>=0.0.5 in /usr/local/lib/python3.10/dist-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==1.1.1->autogluon) (0.0.7)
Requirement already satisfied: fastcore<1.6,>=1.5.29 in /usr/local/lib/python3.10/dist-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==1.1.1->autogluon) (1.5.55)
Requirement already satisfied: fastprogress>=0.2.4 in /usr/local/lib/python3.10/dist-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==1.1.1->autogluon) (1.0.3)
Requirement already satisfied: spacy<4 in /usr/local/lib/python3.10/dist-packages (from fastai<2.8,>=2.3.1->autogluon.tabular[all]==1.1.1->autogluon) (3.7.5)
Requirement already satisfied: future in /usr/local/lib/python3.10/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.1.1->autogluon) (1.0.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.1.1->autogluon) (2.2.1)
Requirement already satisfied: py4j in /usr/local/lib/python3.10/dist-packages (from hyperopt<0.2.8,>=0.2.7->autogluon.core[all]==1.1.1->autogluon) (0.10.9.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2<3.2,>=3.0.3->autogluon.multimodal==1.1.1->autogluon) (2.1.5)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema<4.22,>=4.18->autogluon.multimodal==1.1.1->autogluon) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema<4.22,>=4.18->autogluon.multimodal==1.1.1->autogluon) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema<4.22,>=4.18->autogluon.multimodal==1.1.1->autogluon) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema<4.22,>=4.18->autogluon.multimodal==1.1.1->autogluon) (0.19.1)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from lightning<2.4,>=2.2->autogluon.multimodal==1.1.1->autogluon) (0.11.6)
Requirement already satisfied: numba in /usr/local/lib/python3.10/dist-packages (from mlforecast<0.10.1,>=0.10.0->autogluon.timeseries==1.1.1->autogluon.timeseries[all]==1.1.1->autogluon) (0.60.0)
Requirement already satisfied: window-ops in /usr/local/lib/python3.10/dist-packages (from mlforecast<0.10.1,>=0.10.0->autogluon.timeseries==1.1.1->autogluon.timeseries[all]==1.1.1->autogluon) (0.0.15)
Requirement already satisfied: gdown>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from nlpaug<1.2.0,>=1.1.10->autogluon.multimodal==1.1.1->autogluon) (5.1.0)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk<4.0.0,>=3.4.5->autogluon.multimodal==1.1.1->autogluon) (8.1.7)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk<4.0.0,>=3.4.5->autogluon.multimodal==1.1.1->autogluon) (2024.5.15)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.10/dist-packages (from omegaconf<2.3.0,>=2.1.1->autogluon.multimodal==1.1.1->autogluon) (4.9.3)
Requirement already satisfied: colorama in /usr/local/lib/python3.10/dist-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.1.1->autogluon) (0.4.6)
Requirement already satisfied: model-index in /usr/local/lib/python3.10/dist-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.1.1->autogluon) (0.1.11)
Requirement already satisfied: opendatalab in /usr/local/lib/python3.10/dist-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.1.1->autogluon) (0.0.10)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.1.1->autogluon) (13.7.1)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from openmim<0.4.0,>=0.3.7->autogluon.multimodal==1.1.1->autogluon) (0.9.0)
Requirement already satisfied: coloredlogs in /usr/local/lib/python3.10/dist-packages (from optimum<1.19,>=1.17->optimum[onnxruntime]<1.19,>=1.17; extra == "all"->autogluon.timeseries[all]==1.1.1->autogluon) (15.0.1)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from optimum<1.19,>=1.17->optimum[onnxruntime]<1.19,>=1.17; extra == "all"->autogluon.timeseries[all]==1.1.1->autogluon) (1.13.1)
Requirement already satisfied: onnx in /usr/local/lib/python3.10/dist-packages (from optimum[onnxruntime]<1.19,>=1.17; extra == "all"->autogluon.timeseries[all]==1.1.1->autogluon) (1.16.2)
Requirement already satisfied: onnxruntime>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from optimum[onnxruntime]<1.19,>=1.17; extra == "all"->autogluon.timeseries[all]==1.1.1->autogluon) (1.18.1)
Requirement already satisfied: protobuf>=3.20.1 in /usr/local/lib/python3.10/dist-packages (from optimum[onnxruntime]<1.19,>=1.17; extra == "all"->autogluon.timeseries[all]==1.1.1->autogluon) (3.20.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<2.3.0,>=2.0.0->autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.3.0,>=2.0.0->autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas<2.3.0,>=2.0.0->autogluon.core==1.1.1->autogluon.core[all]==1.1.1->autogluon) (2024.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from ray<2.11,>=2.10.0->ray[default,tune]<2.11,>=2.10.0; extra == "all"->autogluon.core[all]==1.1.1->autogluon) (3.15.4)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ray<2.11,>=2.10.0->ray[default,tune]<2.11,>=2.10.0; extra == "all"->autogluon.core[all]==1.1.1->autogluon) (1.0.8)
Requirement already satisfied: aiosignal in /usr/local/lib/python3.10/dist-packages (from ray<2.11,>=2.10.0->ray[default,tune]<2.11,>=2.10.0; extra == "all"->autogluon.core[all]==1.1.1->autogluon) (1.3.1)
Requirement already satisfied: frozenlist in /usr/local/lib/python3.10/dist-packages (from ray<2.11,>=2.10.0->ray[default,tune]<2.11,>=2.10.0; extra == "all"->autogluon.core[all]==1.1.1->autogluon) (1.4.1)
Requirement already satisfied: aiohttp>=3.7 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<2.11,>=2.10.0; extra == "all"->autogluon.core[all]==1.1.1->autogluon) (3.9.5)
Requirement already satisfied: aiohttp-cors in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<2.11,>=2.10.0; extra == "all"->autogluon.core[all]==1.1.1->autogluon) (0.7.0)
Requirement already satisfied: colorful in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<2.11,>=2.10.0; extra == "all"->autogluon.core[all]==1.1.1->autogluon) (0.5.6)
Requirement already satisfied: py-spy>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<2.11,>=2.10.0; extra == "all"->autogluon.core[all]==1.1.1->autogluon) (0.3.14)
Requirement already satisfied: opencensus in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<2.11,>=2.10.0; extra == "all"->autogluon.core[all]==1.1.1->autogluon) (0.11.4)
Requirement already satisfied: prometheus-client>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from ray[default,tune]<2.11,>=2.10.0; extra == "all"->autogluon.core[all]==1.1.1->autogluon) (0.20.0)

In [3]:
from autogluon.tabular import TabularDataset, TabularPredictor
import time
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import numpy as np
import pandas as pd

In [4]:
train_df = pd.read_csv("/content/Train_set.csv")
test_df = pd.read_csv("/content/Test_set.csv")
submit_df = pd.read_csv("/content/sample_submission.csv")

In [5]:
# train_df = train_df[50:250]
train_df

         _id          Disease  Year    PROVINCE  Week_no  Count
0          1  Hand Foot Mouth  2013     Bangkok        1   62.0
1          2  Hand Foot Mouth  2013     Bangkok        2   95.0
2          3  Hand Foot Mouth  2013     Bangkok        3   88.0
3          4  Hand Foot Mouth  2013     Bangkok        4   86.0
4          5  Hand Foot Mouth  2013     Bangkok        5  132.0
...      ...              ...   ...         ...      ...    ...
32181  32182  Hand Foot Mouth  2020  Narathiwat       48    2.0
32182  32183  Hand Foot Mouth  2020  Narathiwat       49    1.0
32183  32184  Hand Foot Mouth  2020  Narathiwat       50    2.0
32184  32185  Hand Foot Mouth  2020  Narathiwat       51    2.0
32185  32186  Hand Foot Mouth  2020  Narathiwat       52    3.0

[32186 rows x 6 columns]

In [6]:
# test_df = test_df[0:200]
test_df

         _id          Disease  Year    PROVINCE  Week_no
0      32187  Hand Foot Mouth  2021     Bangkok        1
1      32188  Hand Foot Mouth  2021     Bangkok        2
2      32189  Hand Foot Mouth  2021     Bangkok        3
3      32190  Hand Foot Mouth  2021     Bangkok        4
4      32191  Hand Foot Mouth  2021     Bangkok        5
...      ...              ...   ...         ...      ...
11198  43385  Hand Foot Mouth  2023  Narathiwat       37
11199  43386  Hand Foot Mouth  2023  Narathiwat       38
11200  43387  Hand Foot Mouth  2023  Narathiwat       39
11201  43388  Hand Foot Mouth  2023  Narathiwat       40
11202  43389  Hand Foot Mouth  2023  Narathiwat       41

[11203 rows x 5 columns]

In [7]:
combine_df = pd.concat([train_df, test_df])
combine_df

         _id          Disease  Year    PROVINCE  Week_no  Count
0          1  Hand Foot Mouth  2013     Bangkok        1   62.0
1          2  Hand Foot Mouth  2013     Bangkok        2   95.0
2          3  Hand Foot Mouth  2013     Bangkok        3   88.0
3          4  Hand Foot Mouth  2013     Bangkok        4   86.0
4          5  Hand Foot Mouth  2013     Bangkok        5  132.0
...      ...              ...   ...         ...      ...    ...
11198  43385  Hand Foot Mouth  2023  Narathiwat       37    NaN
11199  43386  Hand Foot Mouth  2023  Narathiwat       38    NaN
11200  43387  Hand Foot Mouth  2023  Narathiwat       39    NaN
11201  43388  Hand Foot Mouth  2023  Narathiwat       40    NaN
11202  43389  Hand Foot Mouth  2023  Narathiwat       41    NaN

[43389 rows x 6 columns]

In [8]:
combine_df = combine_df.drop(columns=['Disease'])
combine_df

         _id  Year    PROVINCE  Week_no  Count
0          1  2013     Bangkok        1   62.0
1          2  2013     Bangkok        2   95.0
2          3  2013     Bangkok        3   88.0
3          4  2013     Bangkok        4   86.0
4          5  2013     Bangkok        5  132.0
...      ...   ...         ...      ...    ...
11198  43385  2023  Narathiwat       37    NaN
11199  43386  2023  Narathiwat       38    NaN
11200  43387  2023  Narathiwat       39    NaN
11201  43388  2023  Narathiwat       40    NaN
11202  43389  2023  Narathiwat       41    NaN

[43389 rows x 5 columns]

In [9]:
# Feature engineering on combined data
combine_df['WeekofYear'] = combine_df['Year'] * 100 + combine_df['Week_no']
combine_df['Lag_1'] = combine_df.groupby('PROVINCE')['Count'].shift(1)
combine_df['Lag_2'] = combine_df.groupby('PROVINCE')['Count'].shift(2)
combine_df['Lag_3'] = combine_df.groupby('PROVINCE')['Count'].shift(3)

In [10]:
combine_df = pd.get_dummies(combine_df, columns=['PROVINCE'])
combine_df

,_id,Year,Week_no,Count,WeekofYear,Lag_1,Lag_2,Lag_3,PROVINCE_Amnat Charoen,PROVINCE_Ang Thong,...,PROVINCE_Surin,PROVINCE_Tak,PROVINCE_Trang,PROVINCE_Trat,PROVINCE_Ubon Ratchathani,PROVINCE_Udon Thani,PROVINCE_Uthai Thani,PROVINCE_Uttaradit,PROVINCE_Yala,PROVINCE_Yasothon
0,1,2013,1,62.0,201301,NaN,NaN,NaN,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2,2013,2,95.0,201302,62.0,NaN,NaN,False,False,...,False,False,False,False,False,False,False,False,False,False
2,3,2013,3,88.0,201303,95.0,62.0,NaN,False,False,...,False,False,False,False,False,False,False,False,False,False
3,4,2013,4,86.0,201304,88.0,95.0,62.0,False,False,...,False,False,False,False,False,False,False,False,False,False
4,5,2013,5,132.0,201305,86.0,88.0,95.0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11198,43385,2023,37,NaN,202337,NaN,NaN,NaN,False,False,...,False,False,False,False,False,False,False,False,False,False
11199,43386,2023,38,NaN,202338,NaN,NaN,NaN,False,False,...,False,False,False,False,False,False,False,False,False,False
11200,43387,2023,39,NaN,202339,NaN,NaN,NaN,False,False,...,False,False,False,False,False,False,False,False,False,False
11201,43388,2023,40,NaN,202340,NaN,NaN,NaN,False,False,...,False,False,False,False,False,False,False,False,False,False
11202,43389,2023,41,NaN,202341,NaN,NaN,NaN,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
train_df = combine_df[combine_df['Count'].notna()]
test_df  = combine_df[combine_df['Count'].isna()]

In [12]:
my_list = list(train_df.columns)
my_list.remove('_id')
my_list.remove('Count')
print(my_list)

['Year', 'Week_no', 'WeekofYear', 'Lag_1', 'Lag_2', 'Lag_3', 'PROVINCE_Amnat Charoen', 'PROVINCE_Ang Thong', 'PROVINCE_Bangkok', 'PROVINCE_Bueng Kan', 'PROVINCE_Buriram', 'PROVINCE_Chachoengsao', 'PROVINCE_Chainat', 'PROVINCE_Chaiyaphum', 'PROVINCE_Chanthaburi', 'PROVINCE_Chiang Mai', 'PROVINCE_Chiang Rai', 'PROVINCE_Chonburi', 'PROVINCE_Chumphon', 'PROVINCE_Kalasin', 'PROVINCE_Kamphaeng Phet', 'PROVINCE_Kanchanaburi', 'PROVINCE_Khon Kaen', 'PROVINCE_Krabi', 'PROVINCE_Lampang', 'PROVINCE_Lamphun', 'PROVINCE_Loei', 'PROVINCE_Lopburi', 'PROVINCE_Mae Hong Son', 'PROVINCE_Maha Sarakham', 'PROVINCE_Mukdahan', 'PROVINCE_Nakhon Nayok', 'PROVINCE_Nakhon Pathom', 'PROVINCE_Nakhon Phanom', 'PROVINCE_Nakhon Ratchasima', 'PROVINCE_Nakhon Sawan', 'PROVINCE_Nakhon Si Thammarat', 'PROVINCE_Nan', 'PROVINCE_Narathiwat', 'PROVINCE_Nong Bua Lamphu', 'PROVINCE_Nong Khai', 'PROVINCE_Nonthaburi', 'PROVINCE_Pathum Thani', 'PROVINCE_Pattani', 'PROVINCE_Phang Nga', 'PROVINCE_Phatthalung', 'PROVINCE_Phayao', 'PROVINCE_Phetchabun', 'PROVINCE_Phetchaburi', 'PROVINCE_Phichit', 'PROVINCE_Phitsanulok', 'PROVINCE_Phra Nakhon Si Ayutthaya', 'PROVINCE_Phrae', 'PROVINCE_Phuket', 'PROVINCE_Prachinburi', 'PROVINCE_Prachuap Khiri Khan', 'PROVINCE_Ranong', 'PROVINCE_Ratchaburi', 'PROVINCE_Rayong', 'PROVINCE_Roi Et', 'PROVINCE_Sa Kaeo', 'PROVINCE_Sakon Nakhon', 'PROVINCE_Samut Prakan', 'PROVINCE_Samut Sakhon', 'PROVINCE_Samut Songkhram', 'PROVINCE_Saraburi', 'PROVINCE_Satun', 'PROVINCE_Sing Buri', 'PROVINCE_Sisaket', 'PROVINCE_Songkhla', 'PROVINCE_Sukhothai', 'PROVINCE_Suphan Buri', 'PROVINCE_Surat Thani', 'PROVINCE_Surin', 'PROVINCE_Tak', 'PROVINCE_Trang', 'PROVINCE_Trat', 'PROVINCE_Ubon Ratchathani', 'PROVINCE_Udon Thani', 'PROVINCE_Uthai Thani', 'PROVINCE_Uttaradit', 'PROVINCE_Yala', 'PROVINCE_Yasothon']

In [13]:
# Split the dataset
X = train_df[my_list]
y = train_df['Count']

In [14]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
# Combine the training features and target variable into a single DataFrame
train_data = X_train.copy()
train_data['Count'] = y_train

# Combine the validation features and target variable into a single DataFrame for evaluation
val_data = X_val.copy()
val_data['Count'] = y_val

In [16]:
# Initialize and train the AutoGluon predictor with RMSE as the evaluation metric
predictor = TabularPredictor(label='Count', problem_type='regression', eval_metric='rmse').fit(train_data)

# Evaluate the predictor on the validation data
leaderboard = predictor.leaderboard(val_data, extra_metrics=['rmse'])
leaderboard

No path specified. Models will be saved in: "AutogluonModels/ag-20240802_183734"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.1.1
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024
CPU Count:          12
Memory Avail:       51.02 GB / 52.96 GB (96.3%)
Disk Space Avail:   42.49 GB / 78.19 GB (54.3%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20240802_183734"
Train Data Rows:    25748
Train Data Columns: 83
Label Column:       Count
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    52236.89 MB
	Train Data (Original)  Memory Usage: 3.07 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 77 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', [])  : 77 | ['PROVINCE_Amnat Charoen', 'PROVINCE_Ang Thong', 'PROVINCE_Bangkok', 'PROVINCE_Bueng Kan', 'PROVINCE_Buriram', ...]
		('float', []) :  3 | ['Lag_1', 'Lag_2', 'Lag_3']
		('int', [])   :  3 | ['Year', 'Week_no', 'WeekofYear']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     :  3 | ['Lag_1', 'Lag_2', 'Lag_3']
		('int', [])       :  3 | ['Year', 'Week_no', 'WeekofYear']
		('int', ['bool']) : 77 | ['PROVINCE_Amnat Charoen', 'PROVINCE_Ang Thong', 'PROVINCE_Bangkok', 'PROVINCE_Bueng Kan', 'PROVINCE_Buriram', ...]
	0.6s = Fit runtime
	83 features in original data used to generate 83 features in processed data.
	Train Data (Processed) Memory Usage: 3.07 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.61s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.09709491999378593, Train Rows: 23248, Val Rows: 2500
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 11 L1 models ...
Fitting model: KNeighborsUnif ...
	-10.9382	 = Validation score   (-root_mean_squared_error)
	0.04s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: KNeighborsDist ...
	-10.984	 = Validation score   (-root_mean_squared_error)
	0.04s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBMXT ...
/usr/local/lib/python3.10/dist-packages/dask/dataframe/__init__.py:42: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)

[1000]	valid_set's rmse: 8.19391

	-8.1672	 = Validation score   (-root_mean_squared_error)
	2.62s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBM ...
	-8.0644	 = Validation score   (-root_mean_squared_error)
	0.56s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE ...
	-8.8759	 = Validation score   (-root_mean_squared_error)
	13.19s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: CatBoost ...
	-8.2143	 = Validation score   (-root_mean_squared_error)
	3.13s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesMSE ...
	-8.982	 = Validation score   (-root_mean_squared_error)
	9.44s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	-8.8741	 = Validation score   (-root_mean_squared_error)
	22.82s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: XGBoost ...
	-9.1659	 = Validation score   (-root_mean_squared_error)
	0.87s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	-9.0261	 = Validation score   (-root_mean_squared_error)
	30.04s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMLarge ...
	-8.4954	 = Validation score   (-root_mean_squared_error)
	1.5s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'LightGBM': 0.6, 'LightGBMXT': 0.32, 'NeuralNetTorch': 0.08}
	-8.003	 = Validation score   (-root_mean_squared_error)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 87.09s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 33997.2 rows/s (2500 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240802_183734")

,model,score_test,root_mean_squared_error,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,LightGBMXT,-9.382851,-9.382851,-8.167163,root_mean_squared_error,0.124295,0.050947,2.624732,0.124295,0.050947,2.624732,1,True,3
1,LightGBMLarge,-9.397510,-9.397510,-8.495378,root_mean_squared_error,0.033300,0.011184,1.498337,0.033300,0.011184,1.498337,1,True,11
2,XGBoost,-9.670673,-9.670673,-9.165854,root_mean_squared_error,0.031756,0.010911,0.870366,0.031756,0.010911,0.870366,1,True,9
3,NeuralNetFastAI,-9.682676,-9.682676,-8.874101,root_mean_squared_error,0.175760,0.043171,22.818007,0.175760,0.043171,22.818007,1,True,8
4,CatBoost,-9.739340,-9.739340,-8.214346,root_mean_squared_error,0.065345,0.004072,3.125777,0.065345,0.004072,3.125777,1,True,6
5,WeightedEnsemble_L2,-10.006313,-10.006313,-8.002977,root_mean_squared_error,0.165705,0.073535,33.246449,0.002696,0.000479,0.018137,2,True,12
6,RandomForestMSE,-10.218627,-10.218627,-8.875876,root_mean_squared_error,0.719770,0.100470,13.186184,0.719770,0.100470,13.186184,1,True,5
7,ExtraTreesMSE,-10.289260,-10.289260,-8.981964,root_mean_squared_error,0.756521,0.100888,9.440627,0.756521,0.100888,9.440627,1,True,7
8,LightGBM,-10.638319,-10.638319,-8.064404,root_mean_squared_error,0.010401,0.005454,0.562504,0.010401,0.005454,0.562504,1,True,4
9,NeuralNetTorch,-11.018327,-11.018327,-9.026093,root_mean_squared_error,0.028314,0.016656,30.041075,0.028314,0.016656,30.041075,1,True,10
10,KNeighborsDist,-12.500094,-12.500094,-10.983975,root_mean_squared_error,0.061749,0.029129,0.036331,0.061749,0.029129,0.036331,1,True,2
11,KNeighborsUnif,-12.612435,-12.612435,-10.938235,root_mean_squared_error,0.070923,0.036879,0.041397,0.070923,0.036879,0.041397,1,True,1

In [17]:
from autogluon.tabular import TabularPredictor
from sklearn.metrics import mean_squared_error
import numpy as np

# Define a custom RMSE metric
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

In [18]:
# Get predictions from the best model
y_pred = predictor.predict(X_val)

# Calculate and print the RMSE
rmse_value = rmse(y_val, y_pred)
print(f"RMSE: {rmse_value}")

RMSE: 10.006312875856846

In [19]:
predictor.predict(test_df[test_df['_id']==32191].drop(columns=['_id','Count']))

4    26.954113
Name: Count, dtype: float32

In [20]:
df = pd.read_csv("/content/sample_submission.csv")
df

         _id  Pred
0      32187  32.0
1      32188  13.0
2      32189  17.0
3      32190   NaN
4      32191   NaN
...      ...   ...
11198  43385   NaN
11199  43386   NaN
11200  43387   NaN
11201  43388   NaN
11202  43389   NaN

[11203 rows x 2 columns]

In [21]:
df = pd.read_csv("/content/sample_submission.csv")
for idx,row in df[3:].iterrows():
    data = test_df[test_df['_id']==row['_id']].drop(columns=['_id','Count'])
    result = predictor.predict(data)
    df.at[idx,'Pred'] = result

Streaming output truncated to the last 5000 lines.
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result
<ipython-input-21-eef3a3050055>:5: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  df.at[idx,'Pred'] = result

In [23]:
df

         _id       Pred
0      32187  32.000000
1      32188  13.000000
2      32189  17.000000
3      32190  27.043819
4      32191  26.954113
...      ...        ...
11198  43385  18.370914
11199  43386  18.325590
11200  43387  18.325560
11201  43388  18.429459
11202  43389  17.877943

[11203 rows x 2 columns]

In [22]:
version = '1.0.2'
formatted_time = time.strftime("%H.%M", time.localtime())
formatted_time = str(int(formatted_time.split(".")[0])+7)+formatted_time.split(".")[1]
formatted_time
csv_name = f'v.{version}.{formatted_time}.csv'
print(csv_name)
df.to_csv(csv_name,index=False)

v.1.0.2.2544.csv

In [ ]:
df = pd.read_csv("/content/sample_submission.csv")
for idx,row in df[3:].iterrows():
    data = test_df[test_df['_id']==row['_id']].drop(columns=['_id','Disease'])
    # print(data.PROVINCE)
    province = data.PROVINCE.iloc[0]
    # print(province)
    if province == "Bangkok":
        result = Bangkok.predict(data)
    elif province == "Samut Prakan":
        result = Samut_Prakan.predict(data)
    elif province == "Nonthaburi":
        result = Nonthaburi.predict(data)
    elif province == "Pathum Thani":
        result = Pathum_Thani.predict(data)
    elif province == "Phra Nakhon Si Ayutthaya":
        result = Phra_Nakhon_Si_Ayutthaya.predict(data)
    elif province == "Ang Thong":
        result = Ang_Thong.predict(data)
    elif province == "Lopburi":
        result = Lopburi.predict(data)
    elif province == "Sing Buri":
        result = Sing_Buri.predict(data)
    elif province == "Chainat":
        result = Chainat.predict(data)
    elif province == "Saraburi":
        result = Saraburi.predict(data)
    elif province == "Chonburi":
        result = Chonburi.predict(data)
    elif province == "Rayong":
        result = Rayong.predict(data)
    elif province == "Chanthaburi":
        result = Chanthaburi.predict(data)
    elif province == "Trat":
        result = Trat.predict(data)
    elif province == "Chachoengsao":
        result = Chachoengsao.predict(data)
    elif province == "Prachinburi":
        result = Prachinburi.predict(data)
    elif province == "Nakhon Nayok":
        result = Nakhon_Nayok.predict(data)
    elif province == "Sa Kaeo":
        result = Sa_Kaeo.predict(data)
    elif province == "Nakhon Ratchasima":
        result = Nakhon_Ratchasima.predict(data)
    elif province == "Buriram":
        result = Buriram.predict(data)
    elif province == "Surin":
        result = Surin.predict(data)
    elif province == "Sisaket":
        result = Sisaket.predict(data)
    elif province == "Ubon Ratchathani":
        result = Ubon_Ratchathani.predict(data)
    elif province == "Yasothon":
        result = Yasothon.predict(data)
    elif province == "Chaiyaphum":
        result = Chaiyaphum.predict(data)
    elif province == "Amnat Charoen":
        result = Amnat_Charoen.predict(data)
    elif province == "Bueng Kan":
        result = Bueng_Kan.predict(data)
    elif province == "Nong Bua Lamphu":
        result = Nong_Bua_Lamphu.predict(data)
    elif province == "Khon Kaen":
        result = Khon_Kaen.predict(data)
    elif province == "Udon Thani":
        result = Udon_Thani.predict(data)
    elif province == "Loei":
        result = Loei.predict(data)
    elif province == "Nong Khai":
        result = Nong_Khai.predict(data)
    elif province == "Maha Sarakham":
        result = Maha_Sarakham.predict(data)
    elif province == "Roi Et":
        result = Roi_Et.predict(data)
    elif province == "Kalasin":
        result = Kalasin.predict(data)
    elif province == "Sakon Nakhon":
        result = Sakon_Nakhon.predict(data)
    elif province == "Nakhon Phanom":
        result = Nakhon_Phanom.predict(data)
    elif province == "Mukdahan":
        result = Mukdahan.predict(data)
    elif province == "Chiang Mai":
        result = Chiang_Mai.predict(data)
    elif province == "Lamphun":
        result = Lamphun.predict(data)
    elif province == "Lampang":
        result = Lampang.predict(data)
    elif province == "Uttaradit":
        result = Uttaradit.predict(data)
    elif province == "Phrae":
        result = Phrae.predict(data)
    elif province == "Nan":
        result = Nan.predict(data)
    elif province == "Phayao":
        result = Phayao.predict(data)
    elif province == "Chiang Rai":
        result = Chiang_Rai.predict(data)
    elif province == "Mae Hong Son":
        result = Mae_Hong_Son.predict(data)
    elif province == "Nakhon Sawan":
        result = Nakhon_Sawan.predict(data)
    elif province == "Uthai Thani":
        result = Uthai_Thani.predict(data)
    elif province == "Kamphaeng Phet":
        result = Kamphaeng_Phet.predict(data)
    elif province == "Tak":
        result = Tak.predict(data)
    elif province == "Sukhothai":
        result = Sukhothai.predict(data)
    elif province == "Phitsanulok":
        result = Phitsanulok.predict(data)
    elif province == "Phichit":
        result = Phichit.predict(data)
    elif province == "Phetchabun":
        result = Phetchabun.predict(data)
    elif province == "Ratchaburi":
        result = Ratchaburi.predict(data)
    elif province == "Kanchanaburi":
        result = Kanchanaburi.predict(data)
    elif province == "Suphan Buri":
        result = Suphan_Buri.predict(data)
    elif province == "Nakhon Pathom":
        result = Nakhon_Pathom.predict(data)
    elif province == "Samut Sakhon":
        result = Samut_Sakhon.predict(data)
    elif province == "Samut Songkhram":
        result = Samut_Songkhram.predict(data)
    elif province == "Phetchaburi":
        result = Phetchaburi.predict(data)
    elif province == "Prachuap Khiri Khan":
        result = Prachuap_Khiri_Khan.predict(data)
    elif province == "Nakhon Si Thammarat":
        result = Nakhon_Si_Thammarat.predict(data)
    elif province == "Krabi":
        result = Krabi.predict(data)
    elif province == "Phang Nga":
        result = Phang_Nga.predict(data)
    elif province == "Phuket":
        result = Phuket.predict(data)
    elif province == "Surat Thani":
        result = Surat_Thani.predict(data)
    elif province == "Ranong":
        result = Ranong.predict(data)
    elif province == "Chumphon":
        result = Chumphon.predict(data)
    elif province == "Songkhla":
        result = Songkhla.predict(data)
    elif province == "Satun":
        result = Satun.predict(data)
    elif province == "Trang":
        result = Trang.predict(data)
    elif province == "Phatthalung":
        result = Phatthalung.predict(data)
    elif province == "Pattani":
        result = Pattani.predict(data)
    elif province == "Yala":
        result = Yala.predict(data)
    elif province == "Narathiwat":
        result = Narathiwat.predict(data)
    else:
        print(f"\n\n\nData issue detected in row {idx}. Interrupting process.")
        break

    if result < 0:
        result = 1
    df.at[idx,'Pred'] = result